export { fixImageRadius } from "./fix_image_radius"
export { fixChartHeight } from "./fix_chart_height"
export { fixCircleProcessChart } from "./fix_circle_process_chart"
export { fixTagColors } from "./fix_tag_colors"
export { fixMenuIcons } from "./fix_menu_icons"
export { default as fixChartBuiltinLegend } from "./fix_chart_builtin_legend"
export { default as fixChartData } from "./fix_chart_data"
export { default as fixIconProps } from "./fix_icon_props"
export { default as fixInvalidPaths } from "./fix_invalid_paths"
export { fixDialogClass } from "./fix_dialog_class"
export { default as fixSlotComponents } from "./fix_slot_components"
export { fixStepsFullWidth } from "./fix_steps_full_width"
export { default as fixPatStackedBar } from "./fix_pat_stacked_bar"
export { fixTabContent } from "./fix_tab_content"
export { fixBorderBox } from "./fix_border_box"
